version: '2'
services:
  postgres:
    container_name: postgresql_BFA
    image: postgres
    env_file: ./envs/pg.env
    volumes:
      - pgs:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  bridge:
    container_name: BFA_local
    build:
      context: .
      dockerfile: Dockerfile_local
    command: bash -c "sleep 5 && python manage.py runserver 0.0.0.0:8888"
    volumes:
      - .:/bridge-adaptivity
    ports:
      - "8888:8888"
    links:
      - postgres

volumes:
  pgs:
