version: '2'
services:
  postgres:
    container_name: postgresql_BFA
    image: postgres
    env_file: ./envs/pg.env
    volumes:
      - pgs:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  bridge:
    container_name: BFA
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./prod_run.sh"
    volumes:
      - .:/bridge-adaptivity
      - static:/www/static
    ports:
      - "8000:8000"
    links:
      - postgres
      
  nginx:
    container_name: nginx_BFA
    build: ./nginx
    ports:
      - "8080:80"
    volumes_from:
      - bridge
    links:
      - bridge

volumes:
  pgs:
  static: {}
